name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/books/
